"""empty message

Revision ID: 8a72c698eac8
Revises: 19cf10ed920e
Create Date: 2018-08-05 19:16:25.053964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a72c698eac8'
down_revision = '19cf10ed920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regionName', sa.String(length=32), nullable=False),
    sa.Column('cityCode', sa.Integer(), nullable=False),
    sa.Column('pinYin', sa.String(length=32), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('letters')
    # ### end Alembic commands ###
